x-expert-service-template: &expert-service-template
  build:
    context: ./expert-service
  image: moe-expert-service:latest
  networks:
    - moe-network
  volumes:
    - ./expert-service/app:/app

# --- Service Definitions ---
services:
  # API Gateway Service
  api-gateway:
    build:
      context: ./inference-api-gateway
    image: moe-api-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - moe-network
    environment:
      - SPRING_CODEC_MAX_IN_MEMORY_SIZE=5MB

  # Gating Service
  gating-service:
    build:
      context: ./gating-service
    image: moe-gating-service:latest
    ports:
      # We'll keep this port exposed for now for direct testing.
      - "8000:8000"
    networks:
      - moe-network
  
  # --- Embedding Service ---
  embedding-service:
    build:
      context: ./embedding-service
    image: moe-embedding-service:latest
    ports:
      # Expose on 8009 for direct testing
      - "8009:8000"
    networks:
      - moe-network

  classifier-service:
    build:
      context: ./classifier-service
    image: moe-classifier-service:latest
    ports:
      # Expose on 8010 for direct testing
      - "8010:8000"
    networks:
      - moe-network
    # Add the healthcheck for consistency
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # --- All 8 Expert Services ---
  expert-0:
    <<: *expert-service-template # Merge the template here
    ports:
      - "8001:8001"
    environment:
      - EXPERT_ID=0

  expert-1:
    <<: *expert-service-template
    ports:
      - "8002:8001"
    environment:
      - EXPERT_ID=1

  expert-2:
    <<: *expert-service-template
    ports:
      - "8003:8001"
    environment:
      - EXPERT_ID=2

  expert-3:
    <<: *expert-service-template
    ports:
      - "8004:8001"
    environment:
      - EXPERT_ID=3

  expert-4:
    <<: *expert-service-template
    ports:
      - "8005:8001"
    environment:
      - EXPERT_ID=4
      
  expert-5:
    <<: *expert-service-template
    ports:
      - "8006:8001"
    environment:
      - EXPERT_ID=5

  expert-6:
    <<: *expert-service-template
    ports:
      - "8007:8001"
    environment:
      - EXPERT_ID=6

  expert-7:
    <<: *expert-service-template
    ports:
      - "8008:8001"
    environment:
      - EXPERT_ID=7

networks:
  moe-network:
    driver: bridge